# Generated by Django 5.0.6 on 2024-05-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_rename_subtitles_book_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
